[package]
name = "ora-core"
version = "0.1.0"
edition = "2024"

[features]
test-methods = []

[dependencies]
dirs = "6.0.0"
tempfile = "3.23.0"
thiserror = "2.0.16"
uuid = {version = "1.18.1", features = ["v4"]}

notify = "8.2.0"
rusqlite = "0.37.0"
